site_name: WheelOS  # 网站名称
site_url: https://wheelos.github.io
repo_url: https://github.com/wheelos
theme:
  name: material # 使用 Material 主题
nav:  # 导航栏配置
  - Home: index.md # 首页
  - Quick start: quickstart.md # 快速开始页面
  - Documentation: documentation/index.md # 文档页面
  - Examples: examples.md # 示例页面
  - Resources: resources.md # 资源页面
  - Join: join.md # 加入我们页面
  - About: about.md # 关于我们页面